INSERT INTO DRONE (SERIAL_NUMBER, MODEL, WEIGHT, BATTERY_PERCENTAGE, STATE) VALUES ('XEGYUI', 'Lightweight', 200, 50, 'IDLE'),
('XEGYFDRTYI', 'Lightweight', 300, 70, 'LOADING'),
('XEGYXCDRGU', 'Heavyweight', 250, 55, 'IDLE');